name: Compile file

on:
  push

jobs:
  copmile-file:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo # nome dello step
        uses: action/checkout@v4

      - name: install compiler
        run: sudo apt install gcc

      - name: compile
        run: g++ file.cpp
